### ISSUE TITLE
Only direct connect is working if password is set

### ISSUE THREAD

**Issue by AurimasNav** [StunlockStudios/vrising-dedicated-server-instructions#148]
Similar to many issues already reported, but it seems non of them are making the distinction, that it is working fine when set-up without a password, server is visible in the in-game server list and it connects fine, however once I set up a password it only works via direct connect, trying to connect via in-game server list produces `authentication error`.

My server config:
```yaml
  TZ: Europe/Vilnius
  VR_PASSWORD: somepass
  VR_LIST_ON_STEAM: "true"
  VR_LIST_ON_EOS: "false" #changing to true does nothing for this situation

```
